### ISSUE TITLE
the default shortcut of your plugin conflict with the default shortcut of windows

### ISSUE THREAD

**Issue by phpgit** [idleberg/atom-atomizr#4]
**in windows, these shortcut have different meaning, it conflict with your shortcut, you may consider to change it from Ctrl to Ctrl+Alt+Shift , thanks!**

Memorizing the keyboard shortcuts for conversion is easy. Just think of the s key for Sublime Text and the a key for Atom:

Sublime Text to Atom: Ctrl+s, Ctrl+a (for completions)
Atom to Sublime Text: hold Ctrl+a, Ctrl+s
For automatic conversion, press Ctrl+c twice. To switch the Atom snippet from CSON to JSON (or vice versa), press Ctrl+a twice.

**Comment by idleberg** [comment]
Thanks for reporting, I'll take a look into it

**Comment by idleberg** [comment]
Just to be clear. The problem isn't the shortcuts themselves, but their interference with global shortcuts such as Select All (<kbd>Ctrl</kbd>-<kbd>a</kbd>), Copy (<kbd>Ctrl</kbd>-<kbd>c</kbd>), or Save (<kbd>Ctrl</kbd>-<kbd>s</kbd>). Correct?

**Comment by phpgit** [comment]
Correct, I think you can set these default shourtcut as
(shift-alt-a),(shift-alt-c),(shift-alt-s), it will work well, thanks!

**Comment by idleberg** [comment]
Please give `v0.9.0` a try

**Comment by phpgit** [comment]
Thanks, I will :)
